### PR TITLE
incomplete enumeration of mandatory columns

### PR DESCRIPTION
**Pull request by jo-pol**
fixes incomplete documentation
#### When applied it will
- tell the user all DDM columns are required
#### Where should the reviewer @DANS-KNAW/easy start?

trivial
#### How should this be manually tested?

Try a split-multi-deposit with or without one of de ddm columns followed with an easy-ingest-flow.
#### related pull requests on github

| repo | PR |
| --- | --- |
| easy- | [PR#](PRlink) |

### CODE REVIEW

**Comment by janvanmansum** [comment]
@jo-pol: Just to be sure: have you verified that all the DDM-fields are indeed mandatory?

**Comment by jo-pol** [comment]
I discovered the omission because I I tried a minimal test. We don't have many: `DDM_CREATED`, `DDM_AVAILABLE`, `DDM_AUDIENCE`, `DDM_ACCESSRIGHTS`, `DDM_AUDIENCE`, `DDM_ACCESSRIGHTS`

**Comment by lindareijnhoudt** [comment]
there are 6 fields mandatory in the DDM. 
- description
- title
- creator
- DDM_CREATED, 
- DDM_AUDIENCE, 
- DDM_ACCESSRIGHTS, 

the csv file does not prefix them all with DDM_ though, the title, description and creator are in DC_ and were already mentioned as required elements, so that's ok.

DDM_AVAILABLE is not mandatory, so we do need a list of DDM fields that are required and not a catch-all.

**Comment by rvanheest** [comment]
Is this README change reflected by the code. A.k.a. does SMD complain if you leave out mandatory fields? And is the error message appropriate?

**Comment by jo-pol** [comment]
The error is thrown when ingesting, not by split-multi-deposit. Anyway it is something the user should know. Error handling/reporting is poor on more aspects.

**Comment by rvanheest** [comment]
It is something the user should know, indeed! Preferably as early as possible! So maybe we should consider adding these checks here. Wasn't there an issue in Jira that addresses this?

**Comment by jo-pol** [comment]
You mean [1015](https://drivenbydata.atlassian.net/browse/EASY-1015), it doesn't include these type of checks.

**Comment by rvanheest** [comment]
Then I'd say we should fix it in this PR. We should keep the README consistent with the application's behavior.

**Pull request merged**
